file: /tutorial/adjust-replica-set-member-priority
description: |
  Change the precedence given to a replica set members in an
  election for primary.
---
file: /tutorial/configure-a-non-voting-replica-set-member
description: |
  Create a secondary member that keeps a copy of the data set but does
  not vote in an election.
---
file: /tutorial/convert-secondary-into-arbiter
description: |
  Convert a secondary to an arbiter.
...
